defaults = {
    "base_comps/base_api_key_manager": {
        "Selectedviewer": "icon",
    },
    "base_comps/base_text_to_text": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "Draft a one-sentence synthwave spell to optimize system logic and purge latency.",
        "Autogenerate": False,
    },
    "base_comps/base_text_to_chat": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "In a couple sentences, explain how quartz timing serves as the fundamental ritual for computing precision. Include a citation.",
        "Autogenerate": False,
    },
    "base_comps/base_img_to_text": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "Provide a one-sentence description, focusing on light, energy, or mechanical components.",
        "Autogenerate": False,
    },
    "base_comps/base_text_to_img": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Defaultprompt": "Generate a cinematic shot of a 1980s beige desktop computer pulsing with warm, protective neon magic.",
        "Autogenerate": False,
    },
    "base_comps/base_img_to_img": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "Transform this image into a dreamlike 80s magazine landscape Do not include any words.",
        "Autogenerate": False,
    },
    "base_comps/base_text_to_video": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "A arcane magical glyphs weaving through a 1980s-style grid landscape inside a retro-futuristic monitor.",
        "Autogenerate": False,
    },
    "base_comps/base_image_to_video": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "Transform this image into a vaporwave neon timelapse. ",
        "Autogenerate": False,
    },
    "base_comps/base_audio_to_text": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Tempfile": "",
        "Defaultprompt": "Transcribe this audio, include only the transcription in your response.",
        "Autogenerate": False,
    },
    "base_comps/base_text_to_audio": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "Compose an 80s synthwave track with warm analog pads and a steady beat, representing the magic hum of a computer.",
        "Includeimage": False,
        "Autogenerate": False,
    },
    "base_comps/base_text_to_speech": {
        "Requestid": 0,
        "Generating": False,
        "Hasapikey": False,
        "Selectedviewer": "icon",
        "Callbacksdat": "",
        "Defaultprompt": "[neutral] The quartz crystal drives the system clock. It triggers the logic gates and commands  data flow. [cheerfully] Timing is everything!",
        "Autogenerate": False,
    },
}
