from enum import StrEnum


class GenerationAspectRatio(StrEnum):
    """Gemini Aspect Ratios"""

    ASPECT_1_1 = "1:1"
    ASPECT_1_4 = "1:4"
    ASPECT_1_8 = "1:8"
    ASPECT_2_3 = "2:3"
    ASPECT_3_2 = "3:2"
    ASPECT_3_4 = "3:4"
    ASPECT_4_1 = "4:1"
    ASPECT_4_3 = "4:3"
    ASPECT_4_5 = "4:5"
    ASPECT_5_4 = "5:4"
    ASPECT_8_1 = "8:1"
    ASPECT_9_16 = "9:16"
    ASPECT_16_9 = "16:9"
    ASPECT_21_9 = "21:9"


class GenerationImageSize(StrEnum):
    """Gemini Image Size"""

    # RESOLUTION_512 = "512"
    RESOLUTION_1K = "1K"
    RESOLUTION_2K = "2K"
    RESOLUTION_4K = "4K"


class GenerationThinkingLevel(StrEnum):
    """Gemini Thinking levels"""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class VeoParameterAspectRatio(StrEnum):
    ASPECT_16_9 = "16:9"
    ASPECT_9_16 = "9:16"


class VeoParameterResolution(StrEnum):
    RESOLUTION_720p = "720p"
    RESOLUTION_1080p = "1080p"
    RESOLUTION_4k = "4k"


class VeoParameterDuration(StrEnum):
    # DURATION_4 = "4"
    DURATION_6 = "6"
    DURATION_8 = "8"


class TTSVoiceName(StrEnum):
    ZEPHYR = "Zephyr"
    KORE = "Kore"
    ORUS = "Orus"
    AUTONOE = "Autonoe"
    UMBRIEL = "Umbriel"
    ERINOME = "Erinome"
    LAOMEDEIA = "Laomedeia"
    SCHEDAR = "Schedar"
    ACHIRD = "Achird"
    SADACHBIA = "Sadachbia"
    PUCK = "Puck"
    FENRIR = "Fenrir"
    AOEDE = "Aoede"
    ENCELADUS = "Enceladus"
    ALGIEBA = "Algieba"
    ALGENIB = "Algenib"
    ACHERNAR = "Achernar"
    GACRUX = "Gacrux"
    ZUBENELGENUBI = "Zubenelgenubi"
    SADALTAGER = "Sadaltager"
    CHARON = "Charon"
    LEDA = "Leda"
    CALLIRRHOE = "Callirrhoe"
    IAPETUS = "Iapetus"
    DESPINA = "Despina"
    RASALGETHI = "Rasalgethi"
    ALNILAM = "Alnilam"
    PULCHERRIMA = "Pulcherrima"
    VINDEMIATRIX = "Vindemiatrix"
    SULAFAT = "Sulafat"


class TTSLanguageCode(StrEnum):
    ARABIC = "ar"
    BANGLA = "bn"
    DUTCH = "nl"
    ENGLISH = "en"
    FRENCH = "fr"
    GERMAN = "de"
    HINDI = "hi"
    INDONESIAN = "id"
    ITALIAN = "it"
    JAPANESE = "ja"
    KOREAN = "ko"
    MARATHI = "mr"
    POLISH = "pl"
    PORTUGUESE = "pt"
    ROMANIAN = "ro"
    RUSSIAN = "ru"
    SPANISH = "es"
    TAMIL = "ta"
    TELUGU = "te"
    THAI = "th"
    TURKISH = "tr"
    UKRAINIAN = "uk"
    VIETNAMESE = "vi"
    AFRIKAANS = "af"
    ALBANIAN = "sq"
    AMHARIC = "am"
    ARMENIAN = "hy"
    AZERBAIJANI = "az"
    BASQUE = "eu"
    BELARUSIAN = "be"
    BULGARIAN = "bg"
    BURMESE = "my"
    CATALAN = "ca"
    CEBUANO = "ceb"
    CHINESE_MANDARIN = "cmn"
    CROATIAN = "hr"
    CZECH = "cs"
    DANISH = "da"
    ESTONIAN = "et"
    FILIPINO = "fil"
    FINNISH = "fi"
    GALICIAN = "gl"
    GEORGIAN = "ka"
    GREEK = "el"
    GUJARATI = "gu"
    HAITIAN_CREOLE = "ht"
    HEBREW = "he"
    HUNGARIAN = "hu"
    ICELANDIC = "is"
    JAVANESE = "jv"
    KANNADA = "kn"
    KONKANI = "kok"
    LAO = "lo"
    LATIN = "la"
    LATVIAN = "lv"
    LITHUANIAN = "lt"
    LUXEMBOURGISH = "lb"
    MACEDONIAN = "mk"
    MAITHILI = "mai"
    MALAGASY = "mg"
    MALAY = "ms"
    MALAYALAM = "ml"
    MONGOLIAN = "mn"
    NEPALI = "ne"
    NORWEGIAN_BOKMAL = "nb"
    NORWEGIAN_NYNORSK = "nn"
    ODIA = "or"
    PASHTO = "ps"
    PERSIAN = "fa"
    PUNJABI = "pa"
    SERBIAN = "sr"
    SINDHI = "si"
    SLOVAK = "sk"
    SLOVENIAN = "sl"
    SWAHILI = "sw"
    SWEDISH = "sv"
    URDU = "ur"
